### ISSUE TITLE
Menu Clarification

### ISSUE THREAD

**Issue by dancwilliams** [PippoRJ/hugo-refresh#1]
Hello,

First I want to say that I really like the look of this theme.  Great job!

I am working on testing it and cannot grasp how the menu is created in the top right of the screen.  I did see this line in the documentation:

`The menu is built following the structure of the content folder. Two levels are allowed at the moment.`

Would you be able to provide a little more information to get me going the right direction?  I am used to driving the menu items form the `config.yaml` file, but cannot seem to get that work.  Just wanted to see if I am missing something.

Thanks for the help!

**Comment by PippoRJ** [comment]
Hi @dancwilliams 

Sorry for the delay of my response.
The menu is NOT create following the `config.yaml` but it is created following the file system content of the "content" folder.

Let me show you an example, I hope it helps.
The "content" folder has the following structure:
- Exercises (folder)
- -_index.md (file)
- - Math (folder)
- - - _index.md (file)
- Theories (folder)
- - _index.md (file)

The folder "Exercises" contains the folder "Math" and the file "_index.md". The folder "Math" contains the file "_index.md". The folder "Theories" contains only the file "_index.md".

The top right menu will have 2 items: "Exercises" and "Theories".
Going with the mouse over the "Exercises" it will show the sub-item "Math" that correspond to the sub-folder with the same name.

All the menu items titles are taken from the "title" parameter stored in each "_index.md" file of the same folder.

I hope this clarify it a bit. 
Let me know.

**Comment by dancwilliams** [comment]
Thank you!
