### ISSUE TITLE
Netlify Build failing

### ISSUE THREAD

**Issue by shwetaudacious** [PippoRJ/hugo-refresh#11]
I am deploying my site using Netlify and `Hugo` build is smooth on my windows10 system. However, build in Netlify fails with following stacktrace:

`1:19:34 PM: Building sites …
1:19:34 PM: Total in 331 ms
1:19:34 PM: Error: failed to prune cache "assets": remove /opt/build/repo/resources/_gen/assets/css/css/mycss.css_d11fe7b62c27961c87ecd0f2490357b9.content: no such file or directory
1:19:34 PM: Skipping functions preparation step: no functions directory set
1:19:34 PM: Caching artifacts
1:19:34 PM: Started saving pip cache
1:19:34 PM: Finished saving pip cache
1:19:34 PM: Started saving emacs cask dependencies
1:19:34 PM: Finished saving emacs cask dependencies
1:19:34 PM: Started saving maven dependencies
1:19:34 PM: Finished saving maven dependencies
1:19:34 PM: Started saving boot dependencies
1:19:34 PM: Finished saving boot dependencies
1:19:34 PM: Started saving go dependencies
1:19:34 PM: Finished saving go dependencies
1:19:36 PM: Error running command: Build script returned non-zero exit code: 255
1:19:36 PM: Failing build: Failed to build site
1:19:36 PM: failed during stage 'building site': Build script returned non-zero exit code: 255
1:19:36 PM: Finished processing build request in 13.455972286s`

**Comment by PippoRJ** [comment]
Hi @shwetaudacious 

I am not an expert of Netlify but since it is working well on your machine alone it might be an error related to the Netlify pipeline.

Have a look at these errors:
https://github.com/gohugoio/hugo/issues/5745
https://community.netlify.com/t/hugo-build-failing-after-upgrading-theme-submodule/3241/7
https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/10
Do they help to solve your problem?

**Comment by dunhampa** [comment]
@shwetaudacious if the site is building locally - I just solved a similar Netlify build issue by setting the Hugo version explicitly. See #11 for details.

**Comment by shwetaudacious** [comment]
hey, thanks for suggestion. I was finally able to resolve the issue by removing the unnecessary `resources ` folder. It had some json and css files like above `mycss.css_d11fe7b62c27961c87ecd0f2490357b9.content ` not sure why they were in the same directory.
