### ISSUE TITLE
Feature Request: Add "Home" link on Nav Bar 

### ISSUE THREAD

**Issue by dunhampa** [PippoRJ/hugo-refresh#14]
It might be beneficial to add the option to include Home page (link back to index) on Nav bar via the config file.

I am still learning Hugo so hardcoded in the Nav bar.

**Comment by PippoRJ** [comment]
Hi @dunhampa ,
yes, it might help to add the home page button on the nav bar... 
but I think that the _real_ content of the website are the articles that are always accessible through the navbar and the sidebar, so I am not sure that going back to the homepage is really useful. 
Anyway, I will think about how/where to place it though :)

**Comment by dunhampa** [comment]
@PippoRJ yes, I can appreciate that the home page is more of a splash and once you are in the content the user may not be any reason to go back.

I am modifying the home a bit to provide more content, so that may be driving my request. 

For consideration, here are two blogs I am using for comparison:
https://al-phillips.co.uk/
https://services.informatik.hs-mannheim.de/~nagel/

**Comment by PippoRJ** [comment]
Hi @dunhampa 
both the blog suggested have a lot of content in the homepage, and this is what I was trying to avoid with my theme.
Maybe you can have a look at https://themes.gohugo.io/hugo-fresh/ (Fresh theme). It is a singlepage theme. I modified a lot Fresh theme to obtain my theme but maybe there are parts that you can take to obtain what you want to achieve.

**Comment by dunhampa** [comment]
@PippoRJ  thanks for considering, your response and reason for not including makes sense.
