### ISSUE TITLE
What should I change to fix proportions of preview images?

### ISSUE THREAD

**Issue by ticofab** [PippoRJ/hugo-refresh#17]
My issue is that preview images are stretched to fill the preview area:

<img width="1338" alt="Screenshot 2019-12-29 at 10 15 09" src="https://user-images.githubusercontent.com/1792917/71554784-456a3900-2a24-11ea-932e-9e931191328a.png">

I would like to have them centered and with their proportions unchanged, even if this results in empty space or portions of the image being cropped on one dimension. Where can I change this in the theme? 

Thanks for your pointer. Ideally I would like to then open a PR and make this configurable.

**Comment by ticofab** [comment]
I got it on my branch - removed `height: 100%` from the `figure` class and used `overflow: hidden` on the box.

**Comment by PippoRJ** [comment]
I added the option `keepImageRatio` to the front matter of the posts to force the respect of the image proportions (but the image will still try to fill all the available space).

**Comment by ticofab** [comment]
Awesome, thanks! I merged it into my fork 👍
