### ISSUE TITLE
Theme demo broken on the Hugo Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [PippoRJ/hugo-refresh#20]
Hello @PippoRJ 

The recent commits have broken the theme's demo on the Hugo Themes website.

You have configured the `assetDir` as the `staticDir` and that is not supported by the Hugo Themes architecture.

The breakage happened during the past 14 commits of your repo.

However it is impossible to pinpoint the exact commit since it seems that you are pushing commits in a non-linear order. For example commit https://github.com/PippoRJ/hugo-refresh/commit/61bcf42154a92998a70161e38e953b7f5bd31537 updated the theme's resources before they needed to be updated.

I suggest that in the future before you commit changes test them with the Hugo Themes Build Script. Detailed instructions can be found [here](https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script)

Also you need to fix the demo. As stated in the Hugo Themes [README](https://github.com/gohugoio/hugoThemes#theme-maintenance)

>If a theme demo breaks and remains so for more than 30 calendar days, we may remove it from this repository without further notification.

**Comment by PippoRJ** [comment]
Hi @onedrawingperday ,

Thanks for letting me know. I will update the theme in the upcoming week. As soon as I have done it I will let you know so that you can test it.

Sorry for the mess!

**Comment by PippoRJ** [comment]
Hi @onedrawingperday 

I have removed the `assetDir` option from the example site config and checked the built with the Hugo Themes Build Script.
Can you confirm that everything is correct?

**Comment by onedrawingperday** [comment]
Hell @PippoRJ 

I confirm the fix and I have updated the theme in https://github.com/gohugoio/hugoThemes/commit/2849d084c1ca65c42c6b682c441d01cf220021ab

Thank you for fixing this issue.

**Comment by onedrawingperday** [comment]
@PippoRJ 

The demo is still broken because the resources are outdated and the Themes website is deployed with the basic version of Hugo.

Please regenerate and commit the updated theme's resources.

**Comment by PippoRJ** [comment]
Hi @onedrawingperday ,
this is really strange, I did upload the resources. 
I also regenerated the resources again but there is nothing to commit.
To double check, I removed the extended version of hugo and installed the basic version and I tried to run the demo site and it runs without errors.

**Comment by onedrawingperday** [comment]
What is your local Hugo version?

**Comment by PippoRJ** [comment]
it is `0.62.2`.

**Comment by onedrawingperday** [comment]
I cannot figure out why your theme demo does not generate with the Hugo Themes Build Script, because the console does not print an ERROR.

You need to debug with the basic version of Hugo and to follow these instructions: https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script 

You commented out the `assetDir` from the config but are there any assets in the templates that are dependent from that configuration?

Also the logic in the footer partial uses `isset` and that throws a warning in the console. It would be better if you eliminated that warning by using `with` instead of `isset` for the various footer settings.

Unfortunately I do not have the time to look into this further. Particularly since the commits were in a non linear order and it is not easy to pinpoint the exact commit when the theme broke.

Maybe @digitalcraftsman has the time to look into this.

**Comment by PippoRJ** [comment]
ok, I will remove the warnings.

One recent change that I made is here: https://github.com/PippoRJ/hugo-refresh/blob/master/layouts/partials/single/summary.html#L34 where I am using an hardcoded "content" string to get the size of the image. 
Do you think that this might cause problems?

**Comment by onedrawingperday** [comment]
Iindeed seems that your latest commit masks the console ERRORs.  You should not hardcode the PATH for a theme that is hosted on Hugo Themes. We mention all that in the [README](https://github.com/gohugoio/hugoThemes#common-permalink-issues).

In any case, when I revert the latest 2 commits in your theme's repo by executing `git reset --hard HEAD~2` and then running the Hugo Themes Build Script with the basic version of Hugo I get the following ERROR:
```
Error: Error building site: failed to render pages: render of "home" failed: "/home/alex/work/src/hugoThemes/hugo-refresh/layouts/index.html:33:34": execute of template failed: template: index.html:33:34: executing "main" at <$img.Permalink>: nil pointer evaluating resource.Resource.Permalink
FAILED to create exampleSite for hugo-refresh

```

Once I remove the above lines from `index.html` then I get the following ERROR:
```
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:38:8: executing "main" at <partial "footer.html" .>: error calling partial: "/home/alex/work/src/hugoThemes/hugo-refresh/layouts/partials/footer.html:11:44": execute of template failed: template: partials/footer.html:11:44: executing "partials/footer.html" at <resources.ExecuteAsTemplate>: error calling ExecuteAsTemplate: type <nil> not supported in Resource transformations

```

And so on... 

Apparently this issue is not only a matter of commenting out the `assetDir` parameter in the exampleSite config of your theme, since you are using that setting in the templates to load resources that are then missing.

The Hugo Themes Site does not currently support merging the `assetDir` with the `staticDir` and I doubt it will.

You need to load your theme's resources in a way that the demo generates. I would suggest using either Page Bundles or the default Hugo `assetDir` i.e. `/assets/`

Also as mentioned above you need to test whatever changes you make with the Hugo Themes Build Script locally.

**Comment by PippoRJ** [comment]
> In any case, when I revert the latest 2 commits ....

Why are you testing old versions? With the new commits I try to solve the problems. If you test the old commits the problems are there.
Sorry but maybe I am missing the point here. 

> You need to load your theme's resources in a way that the demo generates. I would suggest using either Page Bundles or the default Hugo `assetDir` i.e. `/assets/`

I am actually using Page Bundles in the example site and the default image (set in the configuration) is actually pointing to the `/assets/` folder.

> Also as mentioned above you need to test whatever changes you make with the Hugo Themes Build Script locally.

I did that but I only get warnings (as you reported as well).

> You should not hardcode the PATH for assets contained in a theme that is hosted on Hugo Themes. 

Yes, I that might be the problem although it is not a absolute path but only relative. I used that I couldn't make the `imageConfig` to work without it. 
I will work on that and I let you know.

**Comment by onedrawingperday** [comment]
>it is not a absolute path but only relative

As mentioned in the README relative hardcoded PATHs point to the host root. The theme demo lives in a subdirectory and Hugo will not be able to serve these assets.

>Why are you testing old versions? With the new commits I try to solve the problems. 

Because the latest commit did not solve the problem and the one about the image ratio is the one that masked the console errors that I mentioned in my previous comment.

**Comment by PippoRJ** [comment]
@onedrawingperday 

I removed the relative path. Let me know if this solves the issue.

I am working to remove warnings given by the `isset` and replacing it with `with` (but it's not always possible if I need to use an else condition).

**Comment by onedrawingperday** [comment]
>I removed the relative path. Let me know if this solves the issue.

@PippoRJ 

The above commit as you see does not solve the problem.

**Comment by onedrawingperday** [comment]
>Let me know if this solves the issue.

@PippoRJ 

The latest commit does not solve the problem.

**Comment by PippoRJ** [comment]
That's super strange.
It is also difficult to debug something that doesn't give me any problem.

I will have a look at the latest 15 commits to see what I changed and see if there is something that can cause problems.

**Comment by PippoRJ** [comment]
@onedrawingperday 

Can you give me more details on the error that it is raised or it does not show any error?

**Comment by onedrawingperday** [comment]
@PippoRJ 

No I cannot give you more details. I am afraid I have already written above what I encountered while trying to debug your theme.

The last commit of your theme that produced a working demo with the Hugo Themes Build Script was aa583af

However I do not have more time to debug this further.

In my opinion the only way to figure out what happened is by going back to the above commit and then introducing the latest changes incrementally and testing with the Hugo Themes Build Script at every step to find out the root cause of the problem.

**Comment by PippoRJ** [comment]
@onedrawingperday 

The problem is that I don't see any error with the Hugo Themes Build Script (only the `isset` warning). 
This means that even If I go back and incrementally add changes I will end up with no errors on my side but still there could be potentially errors on your side. 

Anyway, I will dig more, hopefully I can find something.

**Comment by onedrawingperday** [comment]
>If I go back and incrementally add changes I will end up with no errors on my side but still there could be potentially errors on your side.

That is not the case. If a demo generates locally with the Build Script it will also generate during actual deployment.

**Comment by PippoRJ** [comment]
> The lack of ERRORs is due to something different in the recent re-organization of your theme that the Build Script does not support.

Do you know what is it that the Build Script does not support?
I can't understand what is the problem if there are no errors.

> If you are unable to sort this out I can add your theme to the noDemo array of the Build Script, so that the theme's page only displays the Homepage link with your external demo.

Give me some more time please. I want to dig more into this.

**Comment by PippoRJ** [comment]
@onedrawingperday 

With the extended version of hugo installed, I have launched the Hugo Themes Build Script. 
Instead of raising an error, the missing resources have now been generated.
I have committed these resources.

Is this solving the error?

**Comment by onedrawingperday** [comment]
So this was a matter of missing resources, after all.

Glad you figured it out. 

The demo was fixed on the Hugo Themes website in https://github.com/gohugoio/hugoThemes/commit/c6f116cc18db70b14bfb49634815abf7399ca74d

**Comment by PippoRJ** [comment]
> So this was a matter of missing resources, after all.

Yes indeed. It was strange (at least to me) that the resources generated with the Build Scripts have different names than the one generated by running `hugo server` using the example site as new site.

Thanks a lot for your support!
