### ISSUE TITLE
{.Content} not rendering Headings in List  With Rest Of Theme

### ISSUE THREAD

**Issue by dunhampa** [PippoRJ/hugo-refresh#21]
This is related to a slight theme modification so apologies if not related/supported.

Functionally, I am trying to include content/description of related topics or tags.  That is, for instance if I want to introduce the "code" tags with a general description it would show up when someone clicked the "code" tag. 

Content is displaying but not rendering as expected based on the markdown content.

**Technical Steps:**

I  am using the following steps to create an reproducible example using 'my-site' based on this repos README.

I then updated the _index.md file at:

/content/topic_1/ :

![image](https://user-images.githubusercontent.com/5845872/73600518-25e09780-451f-11ea-9b42-618c020b1445.png)

I then added  `{.Content} ` in the list.html

/my-site/themes/hugo-refresh/layouts/_default/list.html::

here (in list): 

`              <h5 class="subtitle is-5 is-muted">{{- .Params.Subtitle -}}</h5>
              <div class="divider"></div>  
              {{.Content}}   `

The issue I am trying to solve is that the content gets rendered but outside of the theme. For example, the heading H1 get rendered to plain `<h1>` which does not format to a heading in the theme.  It does not render to 
`<h1 class="title section-title">Heading 1</h1>` which is desired.  

This picture shows that the Content is rendered but the headings are not showing as I was expecting (the headings are not formatted):

![image](https://user-images.githubusercontent.com/5845872/73600599-c4212d00-4520-11ea-9a2c-4199952eb1e6.png)

I am investigating on how this gets rendered in Theme but I am stuck.  Any thoughts or help is greatly appreciated.

**Comment by dunhampa** [comment]
I found that by including the Container in the Section had the intended effect:

![image](https://user-images.githubusercontent.com/5845872/73601875-49174100-4537-11ea-92e1-b227e8b8bab3.png)

**Comment by PippoRJ** [comment]
I am glad you figured it out.
Let me know if you have other problems.
