### ISSUE TITLE
There is no way to go back to home

### ISSUE THREAD

**Issue by telecoder** [PippoRJ/hugo-refresh#22]
It appears there is no way to go back to the welcome page once you go to any other page. 

 Am I missing something here?

**Comment by PippoRJ** [comment]
Hi @telecoder , you are right. 
I didn't think that a link to the main page is really necessary as it is not showing anything of the content of the website. You are not the first person that mention this so I will add this link. 
I think I will add this on the top of the page near the right menus.
If you think it should be placed somewhere else let me know.

**Comment by telecoder** [comment]
Thank you for considering this.

I think the most common way for going back to the home page is by clicking on an icon located at the top left corner of the page, just like GitHub does for example. But this would conflict with the location of the tags icon, perhaps both can be located side by side there?.

**Comment by PippoRJ** [comment]
mmm not sure there.. 
I was thinking to add a "Homepage" link the footer under the "Website" column.
Maybe I can add different possibilities in the configuration.

**Comment by PippoRJ** [comment]
Hey @telecoder 
I added 2 options to configure the link to the homepage. In the configuration `config.yaml` under `homepage` setting there are:
- `linkPosition` to specify where the homepage link is placed (options are "none", "menu", "footer" or "menu+footer".) 
- `linkText` to specify the text of the homepage.

**Comment by telecoder** [comment]
Thank you!
