### ISSUE TITLE
Clicking on the homepage link from the About page or the other link does not return to homepage

### ISSUE THREAD

**Issue by escapist21** [PippoRJ/hugo-refresh#24]
The <a href=""> to the Homepage is somehow getting set to parent link itself. Attaching the screenshots from the Chrome page inspector.

![Screen Shot 2020-04-11 at 4 23 11 PM](https://user-images.githubusercontent.com/16124332/79041915-0f3a7900-7c11-11ea-91fe-53a2d2b1eee2.png)
![Screen Shot 2020-04-11 at 4 22 51 PM](https://user-images.githubusercontent.com/16124332/79041918-16fa1d80-7c11-11ea-989a-632d65009963.png)

**Comment by PippoRJ** [comment]
Hi @escapist21 
you are absolutely right. I will fix it in a bit. I'll update you.

**Comment by PippoRJ** [comment]
Hey @escapist21 
I pushed the homepage link fix to the repo.
Let me know if it works for you.

**Comment by escapist21** [comment]
Hey @PippoRJ 
It's working fine now. Thanks for the quick update. Cheers!
