### ISSUE TITLE
While writing python in a code block, a long print statement is breaking the rendering of the markdown.

### ISSUE THREAD

**Issue by escapist21** [PippoRJ/hugo-refresh#25]
A longer print statement messes up with the width of the code block and rest of the markdown while rendering. Attaching screenshots. 

Long print statement in code block

![Screen Shot 2020-04-12 at 11 40 12 AM](https://user-images.githubusercontent.com/16124332/79061948-203bc680-7cb3-11ea-96c6-b47cef2a5ba7.png)

Render with messed up width

![Screen Shot 2020-04-12 at 11 40 33 AM](https://user-images.githubusercontent.com/16124332/79061952-35185a00-7cb3-11ea-8f90-b1ce5a13e9c5.png)

Shorter print statement

![Screen Shot 2020-04-12 at 11 40 57 AM](https://user-images.githubusercontent.com/16124332/79061961-4e210b00-7cb3-11ea-8a98-a5df1de30cd9.png)

Proper render

![Screen Shot 2020-04-12 at 11 41 11 AM](https://user-images.githubusercontent.com/16124332/79061966-6133db00-7cb3-11ea-8cca-3f17035e19ef.png)

My word wrap column width in VScode is set to 80.

Am I missing something or doing something wrong? Or is this an issue that needs to be fixed?

**Comment by PippoRJ** [comment]
Hi @escapist21 
Yes, the traditional way to insert some code might brake the width of the page.
Please use the `code` or `codeWide` shortcodes to insert some code in the page (see the documentation in the README).

**Comment by escapist21** [comment]
Thanks @PippoRJ 

The shortcode `codeWide` works fine. Sorry for the bother.

**Comment by PippoRJ** [comment]
No worries at all!
