### ISSUE TITLE
Shortcode for figure not rendering image 

### ISSUE THREAD

**Issue by escapist21** [PippoRJ/hugo-refresh#27]
My image is stored in the 'images' folder within the static directory, and I have also enabled the _assetDir_ value in the _config.yaml_ file. But using the shortcode for `figure` within the markdown does not render the image. The normal markdown syntax for the image works fine. Attaching screenshots. 

Inspecting the page in Chrome does not show an HTML for the figure shortcode as wel

![Screen Shot 2020-04-12 at 3 04 58 PM](https://user-images.githubusercontent.com/16124332/79065677-d44b4a80-7ccf-11ea-809d-f222773c67fc.png)

![Screen Shot 2020-04-12 at 3 12 58 PM](https://user-images.githubusercontent.com/16124332/79065728-255b3e80-7cd0-11ea-8805-9b1957494f08.png)

![Screen Shot 2020-04-12 at 3 15 45 PM](https://user-images.githubusercontent.com/16124332/79065776-82ef8b00-7cd0-11ea-92ba-3f61aba15d28.png)

**Comment by PippoRJ** [comment]
Hey @escapist21 
The path of an image used in a `figure` shortcode is relative to the leaf bundle path used for that post.
Try that and let me know.

**Comment by escapist21** [comment]
Hey @PippoRJ 
I tried the leaf bundle path solution with my image stored inside the images folder in this manner
*post-title (folder)
--*index.md(file)
--*images(folder)
----*photo.jpeg(file)

inside the index.md I referenced the image in the `figure` shorcode in this manner
`{{%  figure src="images/photo.jpeg" width="500" %}}`
but this doesn't seem to work

the relative path to the summary image in the front matter works fine though

**Comment by PippoRJ** [comment]
This is very strange... Can you give me the link of your repo? So I can have a look..

**Comment by escapist21** [comment]
Okay i got it to work. The short code should be 
`{{< figure src="images/photo.jpeg" width="500" >}}`

I was following the example in the README where it is written as
`{{% figure src="images/photo.jpeg" width="500" %}}`

So basically the readme for both **figure.html** and **twoFigure.html** examples need to be updated.

**Comment by PippoRJ** [comment]
That's great! Thank you for that, I will update the README.
