### ISSUE TITLE
Caption in figures short code?

### ISSUE THREAD

**Issue by escapist21** [PippoRJ/hugo-refresh#28]
This is a feature request. 
Is it possible to add an attribute for caption in the figure shortcode?

something like 
```
<figure>
    <img class="" src="" width="" height="">
    <figcaption>{{- $image.Caption -}}</figcaption>
</figure>
```
should work.

But with my very poor knowledge of Golang I'm really not able to import the "caption" from the "image". The [Hugo shortcode for figure](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/figure.html) also has this feature.

**Comment by PippoRJ** [comment]
Hey @escapist21 , I will have a look on how to add the caption, that shouldn't be too difficult.. I will add this asap..!

**Comment by PippoRJ** [comment]
Hey @escapist21 ,
I added the "caption" element and "alt" property to the figure and twoFigure shortcodes
Let me know!

**Comment by escapist21** [comment]
@PippoRJ Works like a charm. Thanks
