### ISSUE TITLE
Article title

### ISSUE THREAD

**Issue by adlucio87** [PippoRJ/hugo-refresh#30]
Hi,
I'm using your them and thanks, I really like it.
I don't know if it's somethings that I missed or is an issue.
Title in html article page represent always the main website title. I think it could change with main article title. 
Thanks
Andrea

**Comment by PippoRJ** [comment]
Ciao Andrea,
Good catch, I will review it this evening and I will update the theme if necessary.
Cheers

**Comment by PippoRJ** [comment]
I have added the page tittle in addition to the site title in the html tag title

**Comment by adlucio87** [comment]
Thanks for the support!
