### ISSUE TITLE
How to use summaryImage? And what is the default images location?

### ISSUE THREAD

**Issue by kpatnayakuni** [PippoRJ/hugo-refresh#31]
Hello,

Greetings!

This is in continuation to the existing [Issue # 23](https://github.com/PippoRJ/hugo-refresh/issues/23), even I am also in the same scenario, and still didn't understand the working concept of `summaryImage`; so if we want to use `summaryImage` do we have to create a separate leaf bundle for each post and place the images over there? 

Do we have an option to refer to a common location for the summaryImages?

And I have another doubt, what is the images folder where we can keep our images and use them inside the posts?

Thank you and appreciate your help.

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni ,
this folder is an an example of leaf bundle: `hugo-refresh/exampleSite/content/topic_2/example_2_topic_2/` 
Yes, to use the `summaryImage` you need to create a leaf bundle for each post and place the image over there. 
No, there is no common location to store the summary images.

> And I have another doubt, what is the images folder where we can keep our images and use them inside the posts?

If you are referring to the option `assetDir`, this is **only** for the images that you specify in the `config.yaml` file.

Hope ti clarifies a bit better.

**Comment by kpatnayakuni** [comment]
Thank you @PippoRJ! Thanks for the info! Appreciate it.

And sometimes it sticks at the below point and will not up the  server, do you have any idea on this?
```
PS P:\blog> hugo server -D
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.


                   | EN | RU  
-------------------+----+-----
  Pages            | 21 |  5
  Paginator pages  |  0 |  0
  Non-page files   |  2 |  0
  Static files     | 28 | 28
  Processed images |  5 |  0
  Aliases          |  1 |  0
  Sitemaps         |  2 |  1
  Cleaned          |  0 |  0

Built in 1052 ms
Watching for changes in P:\blog\{archetypes,content,data,layouts,static,themes}
```

**Comment by PippoRJ** [comment]
I created a new issue for this other problem so we can close this one.
