### ISSUE TITLE
the server is stuck sometimes

### ISSUE THREAD

**Issue by PippoRJ** [PippoRJ/hugo-refresh#32]
Thank you @PippoRJ! Thanks for the info! Appreciate it.

And sometimes it sticks at the below point and will not up the  server, do you have any idea on this?
```
PS P:\blog> hugo server -D
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.


                   | EN | RU  
-------------------+----+-----
  Pages            | 21 |  5
  Paginator pages  |  0 |  0
  Non-page files   |  2 |  0
  Static files     | 28 | 28
  Processed images |  5 |  0
  Aliases          |  1 |  0
  Sitemaps         |  2 |  1
  Cleaned          |  0 |  0

Built in 1052 ms
Watching for changes in P:\blog\{archetypes,content,data,layouts,static,themes}
```

_Originally posted by @kpatnayakuni in https://github.com/PippoRJ/hugo-refresh/issues/31#issuecomment-638851884_

**Comment by PippoRJ** [comment]
@kpatnayakuni mmm not sure about this.. it never happened to me.. might caused by the content of your site?

**Comment by kpatnayakuni** [comment]
Okay, possible.
I will review it. Thanks again for the help and especially the theme, this is indeed awesome. I owe you, my friend🥇😊.
