### ISSUE TITLE
Localhost is running fine but the published site pages are not opening

### ISSUE THREAD

**Issue by kpatnayakuni** [PippoRJ/hugo-refresh#33]
Hello, I have hosted my site on github pages and it is not loading at all and it freezes at the screen below...
![image](https://user-images.githubusercontent.com/31788728/84007832-96e10180-a98e-11ea-9f66-5affb5c69dd3.png)
With the other theme it is working fine but with this theme it is not working...

But in the localhost it is working fine.

My site repo: https://github.com/kpatnayakuni/blog

My site address hosted on github pages is https://kpatnayakuni.github.io/

Please assist me.
Thank you.

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni ,
This is very strange I will have a look and I will let you know..!

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni 

the problem is that the browser is not accepting the "integrity" property of the CSS and JS files.

To solve this, in your `config.yaml` can you try to set the `baseURL` to `https://kpatnayakuni.github.io/` and deploy the result to github? 
Let me know if it works.

**Comment by kpatnayakuni** [comment]
Hi @PippoRJ,

I have added the baseURL, but still no luck. I have updated in the repo, please take a look.

Thank you.

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni 
ok, I need to update the repo with a fix.. I'll do it this evening.. and I will let you know!

**Comment by kpatnayakuni** [comment]
Hey @PippoRJ 

It looks like the brand new site even without adding any content is going to load the pages.

By the way any luck with the fix?

Thank you.

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni 
Sorry about that, I was super-busy yesterday.. I'll do it today!
Cheers

**Comment by kpatnayakuni** [comment]
Hey @PippoRJ 
It worked like charm.
Thank you for your help, appreciate it!
