### ISSUE TITLE
404 template not working

### ISSUE THREAD

**Issue by uint16** [PippoRJ/hugo-refresh#35]
Going to wrong url doesn't apply the 404 template

**Comment by PippoRJ** [comment]
Hey @uint16 ,
this depends entirely on your web server, it does not depends on the theme. 
You need to properly configure `nginx` or `apache` or the web server that you are using.
If you are using `hugo server` to try the theme, it will not load your 404 page as written here: https://gohugo.io/templates/404/

**Comment by uint16** [comment]
Hi @PippoRJ Thank you so much, I somehow missed that  when reading through the docs!

Cheers.
