### ISSUE TITLE
Search Options

### ISSUE THREAD

**Issue by kpatnayakuni** [PippoRJ/hugo-refresh#36]
Hey @PippoRJ 

Just wondering, is there an option to enable the search feature in the theme?

And do you have any plans to implement the search bar in the near future?

Thank you,
Kiran P.

**Comment by PippoRJ** [comment]
Hey @kpatnayakuni ,
unfortunately this is not in my plans for the near future... I need to understand how to do that.. and where to place it in the page... not sure that yet.. and therefore it might take a big while..
Cheers

**Comment by kpatnayakuni** [comment]
Hey @PippoRJ ,
Completely understandable. Not an issue! 
Thank you.
