### ISSUE TITLE
Issues getting the building to generate a good page

### ISSUE THREAD

**Issue by artfisica** [PippoRJ/hugo-refresh#37]
Hi!

Awesome project! thank you.

I have an issue getting the building of the page.

When I use `hugo server`, it looks good :)

But when using `hugo` I got unformatted pages, like the pic attached.

<img width="977" alt="Screenshot 2020-07-09 02 03 09" src="https://user-images.githubusercontent.com/8846121/86982659-1cbcbc00-c18a-11ea-9b66-152974d3c75f.png">

Have you seen this before?
Thanks

**Comment by artfisica** [comment]
Hi!

Just to give you more context:
This happens when I want to build the repo as it is. I did not modify anything. I simply run `hugo` and try to open the `public/index.html in my browser.

Cheers

**Comment by PippoRJ** [comment]
Hey @artfisica 
yes, that is normal. This is because when you open like that it is not loading all the resources that the page is supposed to be loading (no js, no css). 
If you move those files to a web server it is going to work fine as running `hugo server`
Cheers

**Comment by artfisica** [comment]
Thanks! I used the base URL in the right way. Your comment help me.
