### ISSUE TITLE
not loading the full site in netlify

### ISSUE THREAD

**Issue by rajganeshp** [PippoRJ/hugo-refresh#38]
I like this theme and it works locally, but when i publish to netlify, it's not loading the center content completely. it keeps loading. 
it show the menu correctly.

**Comment by PippoRJ** [comment]
Hey @rajganeshp 
I don't use netlify so I am not sure how can I help you but some time ago another user had a problem with netlify.
Have a look here https://github.com/PippoRJ/hugo-refresh/issues/11 and https://github.com/PippoRJ/hugo-refresh/issues/12 and let me know if this helps. 
Otherwise you can post here the error maybe we can have a look together.

**Comment by rajganeshp** [comment]
thank you for quick response. i am not getting an error. the images are not
loading. take a look at this. https://priyaselvakumar.netlify.app/

**Comment by PippoRJ** [comment]
ah, I see now.
Set the `cssIntegrity` to `false` and `jsIntegrity` to `true` on your `config.yaml`
Let me know if this solves the issue.

**Comment by PippoRJ** [comment]
you might have also not correctly setup the variable `baseURL` on your `config.yaml`.
Check that as well.

**Comment by rajganeshp** [comment]
will check shortly. but what should it be? have two othwr sites with
different themes and i didn-'t change anything.

thanks

**Comment by PippoRJ** [comment]
In your website you have this error:

> Failed to find a valid digest in the 'integrity' attribute for resource 'https://priyaselvakumar.netlify.app/css/refresh.c630d402ce8a6dad0fbd9ea764dd06524ef40fd541bf5264bf3c3cd2b1c0f3e9.css' with computed SHA-256 integrity '0VLeCDxzNCtPgASSfH5EEc3oBEV+d9Oy0ksmai5xGlA='. The resource has been blocked.

So the integrity property makes the resource not accepted.
(You can have more info on the `integrity` here: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)
(Other themes may not set the integrity property, thus they work regardless of your settings.)

The integrity property is also affected by the `baseURL` property of your `config.yaml` file so you need to configure it correctly (this is the solution 1).
To completely bypass the integrity property just turn this feature off by setting `cssIntegrity` to `false` and `jsIntegrity` to `false` on your `config.yaml` (this is the solution 2).

**Comment by rajganeshp** [comment]
I made the changes as below but still it's not loading.
https://priyaselvakumar.netlify.app/    anything else I can check. or is
there another free site i can deploy and try.

baseURL: https://priyaselvakumar.netlify.app
languageCode: en-us
title: Personal website and blog
theme: hugo-refresh
# theme: ../..

cssIntegrity: false
jsIntegrity: false

https://priyaselvakumar.netlify.app/

**Comment by PippoRJ** [comment]
Can you make your site repository visible? and give me the github address.
I will have a look.

**Comment by PippoRJ** [comment]
If your `config.yaml` is similar what you posted you have to check again the parameters `cssIntegrity` and `jsIntegrity` here: https://github.com/PippoRJ/hugo-refresh/blob/master/exampleSite/config.yaml

> params:
>   jsMinify: false
>   cssMinify: false

Those settings are nested settings under `params`.

**Comment by rajganeshp** [comment]
i don't have the config and stuff and just publish the public folder.
https://github.com/rajganeshp/priya

I can send zip and send the whole folder if you want.

Raj

**Comment by PippoRJ** [comment]
Unfortunately I need the whole project including the config because otherwise I can't understand what's going on.

**Comment by rajganeshp** [comment]
Thanks for your support. I like to use this template as it's simple and
elegant. you can download the whole project from this link.
https://drive.google.com/file/d/1245xw---wz-rlTbluzk29FJ4C9inBjpV/view?usp=sharing

**Comment by PippoRJ** [comment]
The repo looks good.
Are you sure you loaded the latest version correctly?
In your https://github.com/rajganeshp/priya/blob/master/index.html there is no `integrity` property in the source code while in your https://priyaselvakumar.netlify.app/ there is. So it seems that you only loaded on netlify the old version.

**Comment by PippoRJ** [comment]
I am glad you were able to make it work!
At the moment I don't have plans for adding those features but maybe in the future I will..!

The only colour you can change is the `mainColour` (on your `config.yaml`) parameter to change the main colour of the theme..!

**Comment by rajganeshp** [comment]
thanks again. is it possible to add blogs?

**Comment by PippoRJ** [comment]
Hugo produces static websites so it does not have a database to store comments and reply.

If by "blog" you mean a place where people can comment and you can reply then this it is not possible.

If by "blog" you mean a place where you can store your own articles then yes, this theme is done exactly for that. Have a look at the example website and try to add your own article.

**Comment by rajganeshp** [comment]
Hi PippoRJ -

Is there a way to hide summary image for blog style articles?

Raj

**Comment by PippoRJ** [comment]
Hi Raj,
Unfortunately it is not possible to hide the summary images at the moment.

**Comment by rajganeshp** [comment]
Thanks for your reply. One more quick question. Where do I store the image
to render in blogs? I have an image in same directory and the blog. But
it's not rendering in browser. Any best practice I should follow?

[image: image.png]

**Comment by rajganeshp** [comment]
I figured out the image issue. Do you know if  it's possible to embed
Airtable forms in Hugo?

Thanks again for your help.
Raj

**Comment by PippoRJ** [comment]
Hey Raj,
unfortunately I don't know much about Airtable but it should be possible.. maybe you can embed it as an iframe...

**Comment by rajganeshp** [comment]
Yeah tried, but it doesn't show in the site. thanks thought

<iframe class="airtable-embed" src="
https://airtable.com/embed/shronU9awLU25xAiK?backgroundColor=blue"
frameborder="0" onmousewheel="" width="100%" height="533"
style="background: transparent; border: 1px solid #ccc;"></iframe>

**Comment by rajganeshp** [comment]
Thanks for simple and clean template. My site is coming on great.
Www.connectthoughts.com

Do you know easy way to create analytics?

RAJ

**Comment by rajganeshp** [comment]
figured it out. thanks.

**Comment by rajganeshp** [comment]
I created a short video series on using your template to create static
sites. I did it for my own benefit, and it's not very good. but thought
will share it with you.

https://www.youtube.com/watch?v=lTl90CfyNhg&list=PL8x5iLUAOOYptYJqZRDofemCe8Jk5UqPN

**Comment by PippoRJ** [comment]
Hey @rajganeshp that is amazing..! 

Thanks a lot for sharing!

**Comment by rajganeshp** [comment]
If it helps 10 people, I'll be happy :) I need to become better at
presenting. Thanks for getting back to me. talk to you, later.

**Comment by rajganeshp** [comment]
Is there a limit on how many articles it can show in a page?
https://www.connectthoughts.com/articles/

I have one more article and it's not showing up.

Thanks,
Raj

**Comment by rajganeshp** [comment]
ignore my previous email.
