### ISSUE TITLE
how to add button for switching language

### ISSUE THREAD

**Issue by WLun001** [PippoRJ/hugo-refresh#39]
Hi, I am new to `hugo`, wondering how to add a button on nav bar for switching language

**Comment by PippoRJ** [comment]
That's a good idea..! I'll work on that..!

**Comment by vBuresh** [comment]
Great! Very necessary

**Comment by PippoRJ** [comment]
Hey @vBuresh  @WLun001 ,
I finally added the switch button to the theme.. it's not final... it will now redirect you to the homepage regardless the page you are current visiting.. but it's a good start I think.. I hope you like it..!
let me know what do you think..!

**Comment by WLun001** [comment]
Hi @PippoRJ , where can I view it?

**Comment by PippoRJ** [comment]
I have pushed a new update on the theme... I think you need to pull to have access to it..

Anyway, I will be a `<select>` on the top right part of the menu:
![Screenshot from 2020-10-18 09-56-48](https://user-images.githubusercontent.com/11695618/96362919-c23be000-1128-11eb-8b29-60c7f24268a0.png)

When open the menu it will shop as this:
![Screenshot from 2020-10-18 09-58-11](https://user-images.githubusercontent.com/11695618/96362927-d384ec80-1128-11eb-89ae-f49240b7aff6.png)

**Comment by vBuresh** [comment]
Great! Thanks

**Comment by PippoRJ** [comment]
I have modified the look because it was not showing nice on device
![Screenshot from 2020-10-18 14-09-18](https://user-images.githubusercontent.com/11695618/96368389-8bc38c80-114b-11eb-8c29-5327f5bcbce3.png)

**Comment by WLun001** [comment]
@PippoRJ looks nice! thanks

**Comment by vBuresh** [comment]
> I have modified the look because it was not showing nice on device
> ![Screenshot from 2020-10-18 14-09-18](https://user-images.githubusercontent.com/11695618/96368389-8bc38c80-114b-11eb-8c29-5327f5bcbce3.png)
It much better! Thanks

**Comment by PippoRJ** [comment]
@vBuresh glad you like it!
