### ISSUE TITLE
How to increase list item font size?

### ISSUE THREAD

**Issue by kpatnayakuni** [PippoRJ/hugo-refresh#42]
Hello @PippoRJ 

Greetings!!

How to increase list item font size in the content page? I couldn't find it in any *.css file, can you please assist me?

Thank you,
Kiran P.

**Comment by ticofab** [comment]
I remember doing something similar in my branch. See this changelist, maybe it helps: https://github.com/ticofab/hugo-refresh/commit/e4de3fe54f76e66a28cf5d142bf101eac0823461

**Comment by kpatnayakuni** [comment]
Perfect! That world with `li`.

Thank you @ticofab !

**Comment by PippoRJ** [comment]
Thank you @ticofab for posting the solution!

**Comment by ticofab** [comment]
Glad it helped!
