### ISSUE TITLE
showInMenu not working?

### ISSUE THREAD

**Issue by ticofab** [PippoRJ/hugo-refresh#44]
Hi @PippoRJ , I believe I have found an issue.
Within `content`, I have a folder called `projects`. I would like to hide that folder in the top-tight menu. So the folder contains an `_index.md` file (`index.md` without a preceding underscore won't work) which contains
```
---
title: "Projects"
showInMenu: false
---
```
Directory with file is here: https://github.com/ticofab/blog/tree/master/content/projects
The issue is that even with the `showInMenu: false` property, the website still shows the entry in the top-right menu, see here: https://ticofab.io/

I tried looking at the code, especially in `navbar.html`, but couldn't see anything wrong, hence I'm opening this issue. Would you have any tip on how to hide the menu entry?

Cheers and thanks for your work and help!

**Comment by PippoRJ** [comment]
Hey @ticofab , I believe that `showInMenu` works only with single pages and not with folders.. 
but that's absolutely a great suggestion and something that I need to add..! I'll try to work on it as soon as I can.!

**Comment by ticofab** [comment]
Oh that explains it - and thanks for considering the suggestion!

**Comment by PippoRJ** [comment]
Hey @ticofab so I have pushed a fix that will now make `showInMenu` option to work also on folders.
Please give it a try and let me know.

**Comment by ticofab** [comment]
Hey @PippoRJ , pulled the fix and it does the job perfectly. Another perfect and swift improvement from your side. Thanks a lot!

**Comment by PippoRJ** [comment]
You are always welcome..! Thanks for your new ideas!
