### ISSUE TITLE
Post preview on Linkedin (feature request or guidance request)

### ISSUE THREAD

**Issue by ticofab** [PippoRJ/hugo-refresh#45]
Hey @PippoRJ , a while ago you made some changes that let the post preview show up on twitter and that was awesome. 
Now I have tried to share something on LinkedIn but it didn't have the same card preview effect.

Would it be a lot of work to make it Linkedin-compatible too? I would like to help, with some guidance from your side.

**Comment by PippoRJ** [comment]
Hey @ticofab 
I believed it was already possible to share a page with the correct preview on linkedin.
I had a look at the requisites to have here: https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en&src=aff-lilpar&veh=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&trk=aff_src.aff-lilpar_c.partners_pkw.123201_plc.adgoal%20GmbH_pcrid.449670_learning&clickid=TanQ9oycWxyOWH6wUx0Mo3EWUkiXfyx%3AmS3HVE0&irgwc=1

The page to be shared needs to have the tags `og:title`, `og:image`, `og:description` and `og:url`. All these tags are defined in the theme page `layouts/partials/meta.html`.

I also found post inspector tool from linkedin to see how a page will look like once shared:
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Frjordaney.is%2Fcode_exercises%2Fbuilding_houses%2F
(With one of my pages it seems to render correctly.)

Maybe you can share your page that seems to have this sharing problem.

**Comment by ticofab** [comment]
@PippoRJ I am sorry, it was my bad indeed. It works perfectly on LinkedIn too and thanks for the post inspector tip. Awesome! Thanks for taking the time to look into all this so thoroughly. Do you have a GitHub Sponsor profile?

**Comment by PippoRJ** [comment]
@ticofab I don't have a GitHub Sponsor profile yet... I didn't know it was a thing to be honest 😄 😄 
I submit the application now but it will take 2 week to be approved they say.
