### ISSUE TITLE
Advice on twoVideos

### ISSUE THREAD

**Issue by ticofab** [PippoRJ/hugo-refresh#46]
Hey @PippoRJ , I could use your advice: I am trying to write a `twoVideos` shortcode and would love it to behave like your `twoFigures` and eventually open a PR to see if you want to merge it.
However I'm getting stuck with something. The code of my `twoVideos.html` is:

```
<div class="columns is-centered container" style="height: 385px;">
    <div class="column is-half">
        <iframe class="youtube-player" type="text/html" width="640" height="385" src="https://www.youtube.com/embed/{{ .Get 0 }}" allowfullscreen frameborder="0"></iframe>
    </div>
    <div class="column is-half">
        <iframe class="youtube-player" type="text/html" width="640" height="385" src="https://www.youtube.com/embed/{{ .Get 1 }}" allowfullscreen frameborder="0"></iframe>
    </div>
</div>
```

But the iframes are displayed too short, their height is stuck at 150.
I tried everything and my best guess is that something in `class="column is-half"` is preventing the correct height.

![Screenshot 2020-10-04 at 13 18 39](https://user-images.githubusercontent.com/1792917/95013980-29936380-0644-11eb-8069-e5941822573a.png)

Would you have any quick advice on this? Thanks!

**Comment by PippoRJ** [comment]
Hey @ticofab 
It seems to be correct at first sight.. let me try and let's see what can be the issue..

**Comment by ticofab** [comment]
Thanks @PippoRJ . I have been experimenting more and in fact I've had troubles resizing youtube's iframe _at all_, and that's something with Hugo rather than your wonderful theme.
So don't spend too much time checking this out and totally feel free to close this issue altogether. Cheers!

**Comment by PippoRJ** [comment]
Hey @ticofab I have something for you :)

```
{{- $id1 := .Get "id1" | default (.Get 0) -}}
{{- $id2 := .Get "id2" | default (.Get 1) -}}
<div class="columns is-centered container">    
    <div class="column is-centered container">
        <div>
            <div style="position:relative;padding-top:56.25%;">
                <iframe src="https://www.youtube.com/embed/{{ $id1 }}" frameborder="0" allowfullscreen
                        style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
            </div>
        </div>
    </div>
    <div class="column is-centered container">
        <div>
            <div style="position:relative;padding-top:56.25%;">
                <iframe src="https://www.youtube.com/embed/{{ $id2 }}" frameborder="0" allowfullscreen
                        style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe>
            </div>
        </div>
    </div>
</div>
```

I think it is a mess to find the right CSS style but it should be ok now.

For your reference I was following this post:
https://jameshfisher.com/2017/08/30/how-do-i-make-a-full-width-iframe/#:~:text=Unlike%20s%2C%20%3C,a%2016%3A9%20aspect%20ratio.

I am not sure all the `div` and classes are needed but I will do more trials...

The css are correct for the 16:9 aspect ratio... If you want to have the 4:3 you need to place the 75% as padding top.

**Comment by ticofab** [comment]
You are a magician @PippoRJ ! It seems to work perfectly. Do you plan to make a release with this shortcode?

**Comment by PippoRJ** [comment]
: -) yes I'll release it as soon possible..!

**Comment by PippoRJ** [comment]
Hey @ticofab ,
I have pushed the twoVideos shortcode to the repo..! I have added some parameters to customize them a bit, those parameters are on the readme...!

**Comment by ticofab** [comment]
Thanks @PippoRJ , I synced my fork already :)
