### ISSUE TITLE
Commenting integration for Blog posts

### ISSUE THREAD

**Issue by stuartlupton** [PippoRJ/hugo-refresh#49]
Hi,

Does your template have support for enabling a commenting plug-in such as Disqus?

**Comment by PippoRJ** [comment]
Hey @stuartlupton 
at this very moment I don't have any specific shortcode for that... but it seems a very nice addition to my theme... I will look at it to see how I can integrate it..! I will let you know once done..!

**Comment by stuartlupton** [comment]
Thanks @PippoRJ 
The theme hugo-theme-hello-friend has this feature integrated perhaps there are some idea's here

Keep up the fantastic work :)

**Comment by PippoRJ** [comment]
Hey @stuartlupton 
I was looking at https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/comments.html but it only says to use the standard hugo comment integration described here: https://gohugo.io/content-management/comments/
Did you try to use this?

**Comment by PippoRJ** [comment]
closed due to inactivity
