### ISSUE TITLE
Error when trying to build a site using this theme.

### ISSUE THREAD

**Issue by jaysgrant** [PippoRJ/hugo-refresh#51]
Please forgive what is probably a very newbie type question.

I'm following the steps at https://gohugo.io/getting-started/quick-start/ to get accustomed on how Hugo works, and I really like this theme.

When I try to run either hugo server -D, or hugo -D I receive the following error output. I'm running this on Windows 10.

I have confirmed that it does work using the ananke theme that the quick start guide uses.

`Start building sites …
ERROR 2020/10/14 17:06:12 render of "home" failed: "themes\refresh\layouts\_default\baseof.html:6:46": execute of template failed: template: index.html:6:46: executing "index.html" at <len $icon>: error calling len: reflect: call of reflect.Value.Type on zero Value
ERROR 2020/10/14 17:06:12 render of "section" failed: "themes\refresh\layouts\_default\baseof.html:6:46": execute of template failed: template: _default/list.html:6:46: executing "_default/list.html" at <len $icon>: error calling len: reflect: call of reflect.Value.Type on zero Value
ERROR 2020/10/14 17:06:12 render of "taxonomy" failed: "themes\refresh\layouts\_default\baseof.html:6:46": execute of template failed: template: _default/terms.html:6:46: executing "_default/terms.html" at <len $icon>: error calling len: reflect: call of reflect.Value.Type on zero Value
ERROR 2020/10/14 17:06:12 render of "taxonomy" failed: "themes\refresh\layouts\_default\baseof.html:6:46": execute of template failed: template: _default/terms.html:6:46: executing "_default/terms.html" at <len $icon>: error calling len: reflect: call of reflect.Value.Type on zero Value
Built in 32 ms
Error: Error building site: failed to render pages: render of "page" failed: "themes\refresh\layouts\_default\baseof.html:6:46": execute of template failed: template: _default/single.html:6:46: executing "_default/single.html" at <len $icon>: error calling len: reflect: call of reflect.Value.Type on zero Value`

**Comment by jaysgrant** [comment]
Reread the documentation, and solved my own problem. I hadn't curled down the proper config file. Closing this.

**Comment by PippoRJ** [comment]
Happy that you were able to solve it..!
