### ISSUE TITLE
enable dark mode

### ISSUE THREAD

**Issue by Ayman-Barghout** [PippoRJ/hugo-refresh#52]
Thanks for the awesome theme, I am having a blast using and customizing it.
My only issue is there is no way to configure dark mode for my website, as a new user to both Bulma css and Hugo itself I am trying to customize the theme to use have dark mode enabled but to no avail.
Any help or directions would be highly appreciated and thanks again for taking your time to provide this great theme for free.

**Comment by PippoRJ** [comment]
Hey @Ayman-Barghout ,
Thanks, I am glad you like it..!
At the moment, in the theme, there are no configuration options to configure the dark mode.. It would be cool to add this..! 
Were you looking to have a button on the page to switch it on the fly? Or a configuration option on Hugo?

**Comment by Ayman-Barghout** [comment]
Thanks for the quick response!
It would be better if the colors can be configured for each in a CSS file but that's not a priority.
So, either would do, do you have any idea of how this can be implemented?

**Comment by PippoRJ** [comment]
Yeah the configuration would be easier I guess.. 
We will need identify the colors to change in the .sass files... And then add them to the main configuration file.. but if you identify the colors to change will be already a great help for me...

**Comment by Ayman-Barghout** [comment]
> Yeah the configuration would be easier I guess..
> We will need identify the colors to change in the .sass files... And then add them to the main configuration file.. but if you identify the colors to change will be already a great help for me...

Will do.
