### ISSUE TITLE
Google Analytics integration

### ISSUE THREAD

**Issue by cloudrace** [PippoRJ/hugo-refresh#53]
Hi,

Thank you for this awesome theme. Much helpful.

Updated the googleAnalytics tag in the config.yaml file and also changed layout/partials/custom_head.html to include     {{ template "_internal/google_analytics.html" . }}.

However the integration is not successful.

Could you please advice what I am missing?

Thanks!

**Comment by PippoRJ** [comment]
Hey @cloudrace thanks!
I think you need to enter your Google statistic counter code into the layouts/partials/counter.html
I don't think you need to change any config settings.
Let me know how it goes

**Comment by cloudrace** [comment]
Hi,

I did try that. And it did not work. Reference [here](https://github.com/cloudrace/cloudrace.github.io)

**Comment by cloudrace** [comment]
If I understand this correctly, the index.html files should be created with the google analytics script? I dont see them being used after I run hugo

**Comment by PippoRJ** [comment]
It seems correct how you did it on your reference.. where do you deploy your code? What is the address of your site?

**Comment by cloudrace** [comment]
[cloudrace.info](https://cloudrace.info)

**Comment by PippoRJ** [comment]
when running `hugo server -D` I see these warnings:

> WARN 2021/01/14 19:35:16 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2021/01/14 19:35:16 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2021/01/14 19:35:16 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
>

**Comment by cloudrace** [comment]
I do not see any.

Here is my successful run 
![image](https://user-images.githubusercontent.com/76705579/104641157-69bca600-5677-11eb-8c95-5b7507cfed6b.png)

**Comment by PippoRJ** [comment]
which version of hugo are you using?

**Comment by cloudrace** [comment]
Hugo Static Site Generator v0.80.0/extended linux/amd64 BuildDate: 2020-12-31T20:02:59Z

**Comment by PippoRJ** [comment]
I got the error now.
You need to modify the page `layouts/partials/counter.html` of the theme not of your site.
You need to modify the file `cloudrace.github.io/themes/hugo-refresh/layouts/partials/counter.html` and not the file `cloudrace.github.io/layouts/partials/counter.html`. 
You can delete the file `cloudrace.github.io/layouts/partials/counter.html` it is not used.

**Comment by cloudrace** [comment]
Thank you. Let me try that.

**Comment by cloudrace** [comment]
That worked perfectly. Thank you so much for your time. Sincerely appreciate it.

**Comment by cloudrace** [comment]
Please accept my sincere one time sponsorship. Thank you so much. You saved me a ton of time. Please keep up the great work

**Comment by PippoRJ** [comment]
No worry at all! Glad to help!
