### ISSUE TITLE
Mermaid.js support for diagrams(sequence, graphs, charts etc.)

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#54]
Hi, Thanks for the awesome theme 👍 . Really like it . Are are thinking to include diagram support via mermaid.js.

**Comment by PippoRJ** [comment]
Hey @dharmjit thanks.
I have not planned yet any specific support for that. I believe you can add the that js in the custom head section so you can use it in the normal pages. Let me know how it goes.

**Comment by dharmjit** [comment]
Hi @PippoRJ , It kind of worked by adding shortcode and mermaid.js. There are still some style issues. Is it in the roadmap to add mermaid support.

**Comment by PippoRJ** [comment]
Hey @dharmjit ,
no, it is not in the roadmap unfortunately. There are too many JS libraries and trying to support all of them will become impossible to deal with especially if they have conflicts. 
Feel free to change the style will make mermaid works, of course.
