### ISSUE TITLE
Use markdown code syntax highlighting with three backticks

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#55]
Hi, Is it possible to use three backticks for code syntax highlighting with this themeas in below example. I need to use `{{< codeWide language="go" >}}` but wit this I loses highlighting in VS Code.
\```go
package main

import (
	"fmt"
	"time"
)
func main() {
	go hello()
	time.Sleep(time.Second * 1)
}
func hello() {
	fmt.Println("Hello World")
}
\```

**Comment by PippoRJ** [comment]
Hey @dharmjit ,
Yes, VS Code is not able to highlight the syntax between the `codeWide` elements. 
You can still see the highlight in the rendered page.
