### ISSUE TITLE
How to create Tiles as in demo application 

### ISSUE THREAD

**Issue by dharmjit** [PippoRJ/hugo-refresh#57]
Hi, Is it possible to create **tiles** as in https://rjordaney.is/about/ under Interests section for skills.

Thanks

**Comment by PippoRJ** [comment]
Hey @dharmjit ,

yes you can create those.
Unfortunately I haven't created a shortcode yet, but you can use this code directly in your `.md` file:
`<a><span class="tag title is-6 is-light">Machine Learning</span></a>`

Thanks for the suggestion, I am going to create a shortcode for it.

**Comment by dharmjit** [comment]
Need to use below to make raw html rendering
```
markup: 
  goldmark:
    renderer:
      unsafe: true
```

**Comment by PippoRJ** [comment]
oh yes, that's correct. Good spot.
