### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by Michel69-de** [PippoRJ/hugo-refresh#58]
First of all, i love your theme.
[My site](https://www.schiraumtechnik.com) stuck on Drupal 7 and i plan to rebuild it with hugo.
I also have startet a [food blog](http://kitchen.fuchsia-lodge.de) for my wife and your theme matches best.
For now i have some trouble getting [List All Available Languages](https://gohugo.io/content-management/multilingual/#list-all-available-languages) and [Reference the Translated Content](https://gohugo.io/content-management/multilingual/#reference-the-translated-content) combined so if a translation exist it links to this an if not it links to the Homepage. Can you help me out with it?

Greetings Michael

**Comment by PippoRJ** [comment]
Hey @Michel69-de thanks! 
So, those links concerns about the development of a theme... they are not really about writing the content using a theme. 
There are 2 ways of translating the content of a theme: https://gohugo.io/content-management/multilingual/#translate-your-content
What I can suggest is writing the pages using this feature https://gohugo.io/content-management/multilingual/#translation-by-filename 
In this way you have one file in one language and one file in another.
If an article is missing in a specific language and you want to replace it with another language, you can just copy the file of the other language and rename it.

Hope it helps

**Comment by Michel69-de** [comment]
I think i have to make the Issue more clearly.

I do have translated content by filename.

If I put the following Code in your _navbar.html_  and a translation exist, **.Permalink** points to the translated page. Otherwise the link dont appear.

`<!-- Testcode -->`
`<ul>`
`   {{ range .Translations }}`
`    <li>    <a href="{{ .Permalink }}">{{ .Lang }}</a>`
`    {{ end }}`
`</ul>`
`<!-- End -->`

`                {{ range $.Site.Home.AllTranslations }}`
`...`

If I put the Code into the existing range, **.Permalink** points to the Homepage of the Language.
So **.Permalink** changes his Context and I dont know how to solve this so far.

**Comment by PippoRJ** [comment]
I think you need to share the code otherwise it will be difficult for me to understand. Can you make your github repo public?

> If I put the Code into the existing range...

Where do you want to put this code?

**Comment by Michel69-de** [comment]
I'm new to GitHub and don't have a repo. Sorry for the inconviniences I may caused.
[I try to use your code](https://github.com/PippoRJ/hugo-refresh/commit/b19389b375a456f29146dc0311133976af9537b1)
Hope that's ok.

**Comment by PippoRJ** [comment]
No problem at all... of course you can use and modify the code as you please..
I have commented the on code link you posted.. let  me know if it helps

**Comment by Michel69-de** [comment]
Thanks so far but that is not the point I mean. Let me think about another way to explain it.

**Comment by Michel69-de** [comment]
Abstract:
There is a multilingual Website. For this Website there has to be a Language switch. If a translation exists, i can use the Language switch to get onto the translated page.
Maybe not all pages will be translated in all used languages. If so, the Language switch should exist anyway and should get me to the frontpage.

**Comment by PippoRJ** [comment]
I think I understood:

`
                  {{ $allLanguage := slice }}
                  {{ $translatedLanguage := slice }}
                  {{ range $.Site.Home.AllTranslations }}
                    {{ $allLanguage = $allLanguage | append .Language.Lang }}
                  {{ end }}
                  {{ range .Translations }}
                    {{ $translatedLanguage = $translatedLanguage | append .Language.Lang }}
                    <li> <a href="{{ .Permalink }}"> {{ .Lang }} </a></li>
                  {{ end }}

                  {{ range $.Site.Home.AllTranslations }}
                    {{ if ne $currentLang .Language.Lang }}
                      {{ if not (in $translatedLanguage .Language.Lang) }}
                        <li> <a href="{{ .Permalink }}"> {{ .Lang }} </a></li>
                      {{ end }}
                    {{ end }}
                  {{ end }}
`
(I think there are more elegant ways to do this.. but it is working)

I will add this to the theme... it is something that I meant to add in a while

**Comment by PippoRJ** [comment]
I pushed it to the theme.... you can use it now!

**Comment by Michel69-de** [comment]
Bravo! That's exactly it!
