### ISSUE TITLE
Adding German to languages

### ISSUE THREAD

**Issue by PippoRJ** [PippoRJ/hugo-refresh#59]
Hey @Michel69-de

I would like to add the German language to my theme, I was wandering if you think that these translations are correct:

"Read more" --> Weiterlesen
"Menu" --> Menü
"All Tags" --> Alle Stichworte
"Tags" --> Stichworte
"Last modified" --> Zuletzt geändert
"Website" --> Webseite
"Credits" --> Credits
"Copyright" --> Copyright
"Contacts" --> Kontakte
"Homepage" --> Homepage

(I hope you don't mind me asking since your websites are in German)

**Comment by Michel69-de** [comment]
My wife suggest to translate Credits --> Impressum

The rest shoud be fine.

"Read more" --> Weiterlesen
"Menu" --> Menü
"All Tags" --> Alle Stichworte
"Tags" --> Stichworte
"Last modified" --> Zuletzt geändert
"Website" --> Webseite
"Credits" --> Impressum
"Copyright" --> Copyright
"Contacts" --> Kontakte
"Homepage" --> Homepage

**Comment by PippoRJ** [comment]
amazing thanks... I have included the language translation file now..!
