### ISSUE TITLE
Images not working after latest Hugo upgrades - resource.Resource nil pointer

### ISSUE THREAD

**Issue by elamje** [PippoRJ/hugo-refresh#6]
```2019/10/22 16:48:06 Failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:22:28: executing "main" at <partial "single/summary.html" .>: error calling partial: "/Users/project/themes/hugo-refresh/layouts/partials/single/summary.html:8:42": execute of template failed: template: partials/single/summary.html:8:42: executing "partials/single/summary.html" at <$image.Resize>: nil pointer evaluating resource.Resource.Resize```

The above error is one of several errors I am getting when I try to reference images in my /static/ or /public/images/ folders. All of them come down to a nil pointer on resource.Resource because apparently those images cannot be found. 

The above example is caused by simply adding a ```post``` content, and overriding the summaryImage variable to summaryImage: images/file.png.

**Comment by elamje** [comment]
Here is a relevant support discussion about the breaking changes in one of the latest releases. https://discourse.gohugo.io/t/nil-pointer-evaluating-resource-resource-resize-in-version-0-57-0/20208

**Comment by PippoRJ** [comment]
Hi @elamje 
the images used in the summary should not be placed in the `static/` or `public/images`.
To reference an image using the `summaryImage` variable you need to use a leaf bundle and reference the image relative to the index.md file.

A leaf bundle is a `post` made in this way:
* folder_1
   * index.md
   * my-image.jpg

The content of the index.md is:
--------------
...
summaryImage: my-image.jpg
...
--------------

Have a look at the exampleSite of the theme here: 
`hugo-refresh/exampleSite/content/topic_1/example_3_topic_1`

Let me know if you manage to make it.

**Comment by elamje** [comment]
Okay, thanks for the help. You were correct about the leaf bundle. I am confused about the other case when I get that ```nil pointer``` error however. 

It arises when I override the 
```
homepage
image: "static/customphoto.png"
```
Where is this homepage looking for the photo? The exampleSite doesn't seem to use the leaf bundle format. Is there documentation on where the config.yaml file looks for resources?

Thanks

**Comment by elamje** [comment]
Okay, thanks for the help! I figured out some things I missed in the documentation. I got past those issues now.
