### ISSUE TITLE
custom summaryImage

### ISSUE THREAD

**Issue by Michel69-de** [PippoRJ/hugo-refresh#60]
I run in an rebuild failure while mistyping the filename of **summaryImage** in **Page-level Params**.
The following modificationes uses the **defaultImage** if the filename is mistyped:

layouts/partial/single/summary.html
```` 
20 - {{- if .Params.summaryImage -}}
20 + {{- if (.Page.Resources.GetMatch (string .Params.summaryImage)) -}}
````

layouts/partial/meta.html
```` 
22 - {{- if .Params.summaryImage -}}
22 + {{- if (.Page.Resources.GetMatch (string .Params.summaryImage)) -}}
````

**Comment by PippoRJ** [comment]
hey @Michel69-de,
yeah that a good suggestion..!
But I think I won't include this in the theme because I prefer the user to be notified straight away about the error... Especially if someone is using automated deploy pipelines (e.g.: Netlify) they might realise the mistake very late..

**Comment by Michel69-de** [comment]
o.k.
