### ISSUE TITLE
resize "summaryImage"'s on "All Tags" page

### ISSUE THREAD

**Issue by Michel69-de** [PippoRJ/hugo-refresh#61]
I found an issue on the **All Tags** page. The summary boxes of different tags do have different sizes. is this a bug or a feature?

![Refresh-resize-all_tags](https://user-images.githubusercontent.com/79600221/110202438-e8101a00-7e68-11eb-98db-e93118bcc6bb.jpg)

**Comment by PippoRJ** [comment]
Hey @Michel69-de that's definitely not a feature! XD
What browser/version are you using? 
I can see the problem in the android version of Chrome (using "Desktop Site") but not in the desktop version of Chrome..

**Comment by Michel69-de** [comment]
Win10
Google Chrome
Version 89.0.4389.82 (Offizieller Build) (64-Bit)

Opera
Version:74.0.3911.203

Microsoft Edge
Version 89.0.774.45 (Offizielles Build) (64-Bit)

MacOS
Safari
Version 14.0.3 (16610.4.3.1.4)

It seems to happen on screen width between 769px-1023px but only on the **All Tags** page so in my opinion there is something with the usage of the responsive settings.

**Comment by Michel69-de** [comment]
After some research i found this:
Comparing *layouts\\_default\terms.html* with *layouts\\_default\list.html* I found an extra `<div></div>` container.

    layouts\_default\terms.html
    
    12 -   <div class="columns">
    32 -   </div>

After removing it looks like its fixed.

**Comment by PippoRJ** [comment]
Hey @Michel69-de  yes, that fixed it! 
Amazing thanks! If you open a pull request I can attribute the fix to you...!

**Comment by Michel69-de** [comment]
As I mentioned I'm new to github and don't know much about _pull request_ and stuff like that.
My intension is to save other peoples livetime by sharing my recognitions so I would welcome it if you like to share.

**Comment by PippoRJ** [comment]
yeah that's always welcome!
