### ISSUE TITLE
Telegram link in the footer

### ISSUE THREAD

**Issue by evocthurner** [PippoRJ/hugo-refresh#64]
Is there a plan to add the Telegram link to a channel in the footer?
Thank you very much.

**Comment by PippoRJ** [comment]
Hey @evocthurner ,
Yeah that's a good idea.. i will look into it... I'll add this week!

**Comment by PippoRJ** [comment]
Hey @evocthurner ,
sorry for being late but it turned out I needed to update my css as well for that.. and I was busy this period.
Do you know what is the prefix for telegram links? This is because in the configuration you will just need to add the suffix.
