### ISSUE TITLE
Including portuguese language

### ISSUE THREAD

**Issue by loyannec** [PippoRJ/hugo-refresh#67]
First, thanks for this amazing theme. I would like to know how can I include Portuguese as a language in this template.

**Comment by PippoRJ** [comment]
Hey @loyannec ,
thanks! So there are 2 ways to do that:
1. You can submit a file called `pt.yaml` with the translation as PR in the folder `i18n` of this theme. Look at the structure of the other files in the same folder and you will understand how to do it. If you do this, you will become a contributor of the theme.
2. You can write here the translation for the following words: 
"Read more" --> 
"Menu" --> 
"All Tags" --> 
"Tags" --> 
"Last modified" --> 
"Website" -->
"Credits" --> 
"Copyright" -->
"Contacts" --> 
"Homepage" -->
One you write down the translations I will update the theme. 
Do as you prefer.
