### ISSUE TITLE
Support for comments

### ISSUE THREAD

**Issue by sameer9nov** [PippoRJ/hugo-refresh#68]
Hey @PippoRJ , thanks for this amazing theme. It is clean and precise and to the point. I used it for my first blog site that I hosted on netlify. Any plans for enhancing the theme to include comments ? Using disqus or others ? I was trying to tinker around a bit but  it hasn't worked for me yet. While I did have a look at the other themes but I would want to stick with this. Do you think [this](https://github.com/rstudio/blogdown/issues/52) could potentially work ? Thanks in advance.

**Comment by PippoRJ** [comment]
Hey @sameer9nov , 
I did have a look at comments a while ago.
I was looking at https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/comments.html but here it only says to use the standard hugo comment integration described here: https://gohugo.io/content-management/comments/
Did you try to use this?

**Comment by sameer9nov** [comment]
Thanks@PippoRJ , I will surely have a look. Will get back with how the trial goes. And again, thanks for the amazing template.

**Comment by sameer9nov** [comment]
No luck there @PippoRJ . I am going to try integrating staticman in here. Let's see how it goes.

**Comment by PippoRJ** [comment]
Hey @sameer9nov , did you had any luck with the integration of staticman?

**Comment by sameer9nov** [comment]
Hey @PippoRJ , I think I am half way through it.  I have setup the bridge to heroku with a bot account and integrated it with my repository. I still need to set up  the htmls for the staticman. Sorry abt the delay. If it's about marking the issue closed, please go ahead. I think I will anyway reach out to you once I am done with the integration and tests. Thanks again @PippoRJ

**Comment by PippoRJ** [comment]
ok perfect, then I'll close this issue and feel free to reopen it whenever you want.
