### ISSUE TITLE
Firefox and Safari cutting off letters from refresh-summary-title elements

### ISSUE THREAD

**Issue by elamje** [PippoRJ/hugo-refresh#7]
When using the post format with an index page that has all of your posts listed with a tile image, a title, and a summary, it seems major browsers are chopping off lowercase letters like "g" and "y" which drop down below the title line.

The element that the issue arises is: 
```html
<h3 class="title is-5 refresh-summary-title">
        Title
</h3>
```
 
You can look at the refresh demo website to see an example of this on the "Post" page. Most of the titles have a letter or two that look strange.

**Comment by PippoRJ** [comment]
Hi @elamje 
you are right. 
It is one of those things that I left to be solved later since it was a minor issue to me (because it doesn't prevent the title to be read or understood).
I will have a look at it this evening, I need to refresh my rusty CSS skills.

**Comment by PippoRJ** [comment]
I update the CSS. 
You should be able to see those letters.

**Comment by elamje** [comment]
Awesome! Thanks for fixing that 🥇 It's looking good.
