### ISSUE TITLE
Summary images for the pages

### ISSUE THREAD

**Issue by cloudrace** [PippoRJ/hugo-refresh#72]
Hi, 

I am unable to provide a summary image for each of the posts. Would you please suggest where the images needs to be placed and added ?

Thanks

For example: please refer to (https://cloudrace.info/machine-learning/) and the code available in (https://github.com/cloudrace/cloudrace.github.io)

**Comment by PippoRJ** [comment]
Hi @cloudrace ,

try to organise the post as described here: https://github.com/PippoRJ/hugo-refresh#customization-options-for-a-regular-page

There is an example in the theme: https://github.com/PippoRJ/hugo-refresh/tree/master/exampleSite/content/topic_1/example_3_topic_1

Let me know if you need more help.

**Comment by cloudrace** [comment]
Hi,

I am experiencing the same error as referenced in this [link](https://github.com/PippoRJ/hugo-refresh/issues/6). My folder structure and image placement looks as suggested but the error remains the same.

Please advice how to overcome this.

<img width="1062" alt="error" src="https://user-images.githubusercontent.com/76705579/121822662-49b50100-cc6e-11eb-9034-389bed257397.png">

Actual Error message
<img width="1103" alt="error3" src="https://user-images.githubusercontent.com/76705579/121822686-681afc80-cc6e-11eb-984b-24fdfe762df0.png">

**Comment by PippoRJ** [comment]
Hey @cloudrace ,
try to rename `how_to_get_handson.md` to `index.md`.
If this doesn't help I will download your repo and have a look.
Let me know.

**Comment by cloudrace** [comment]
Thank you! That worked. Appreciate you jumping in
