### ISSUE TITLE
Demo contents shows wrong code blocks

### ISSUE THREAD

**Issue by Thanatermesis** [PippoRJ/hugo-refresh#76]
I'm running the demo site as the instructions explained for the exampleSite directory and I'm seeing that the code blocks looks to have a wrong design (big space on the numbers element):

![image](https://user-images.githubusercontent.com/1181626/163218280-1f8f1539-027a-471f-b620-e929a23d947c.png)

**Comment by PippoRJ** [comment]
Hi,
Thanks for reporting that.
I will have a look as soon as I can (probably next week).

**Comment by PippoRJ** [comment]
Hi @Thanatermesis ,
I fixed the example, it is now using a shortcode that I created.
