### ISSUE TITLE
Can't change default font-famliy with the variables in config.yaml

### ISSUE THREAD

**Issue by yofeng2021** [PippoRJ/hugo-refresh#77]
I have tried to change the default page `font-familiy` to `Noto Sans SC`, but it doesn't work well. The page's default font-family is stil `Open Sans`. I checked the config.toml and some sass files and find there are some diffrerents between the variables' name. So I want to ask that do you write the variables in config.toml correctly?

**Comment by PippoRJ** [comment]
Hey,
I need to check that. I do not remember this detail. I will let you know in
the coming days.

**Comment by PippoRJ** [comment]
it seems to be working fine to me... you need to change the fond in the `mainPage` `sidebar` and `navbar` in the `config.yaml`...
What are the differences you see in the variables' name?
