### ISSUE TITLE
How do I add a link back to the home page?

### ISSUE THREAD

**Issue by Aryan-Naveen** [PippoRJ/hugo-refresh#78]
I was wondering if there is a modification in config.yaml I can make so that a link back to homepage is available?

**Comment by PippoRJ** [comment]
Hey,
where do you want to place that link? In the top menu? In the bottom
footer? In the tag list? In a document?

**Comment by Aryan-Naveen** [comment]
In the top menu.

**Comment by PippoRJ** [comment]
in the `config.yaml` you can use the option `linkPosition` and `linkText` of the `homepage` configuration.
see the commented code in the example here: https://github.com/PippoRJ/hugo-refresh/blob/master/exampleSite/config.yaml#L105
Let me know if it works so I can close the issue

**Comment by Aryan-Naveen** [comment]
Ah thank you!!
