### ISSUE TITLE
please add home redirect and help to bring blogs in place of tags

### ISSUE THREAD

**Issue by harshnandwana** [PippoRJ/hugo-refresh#80]
1.can you please make a button to redirect to homepage from blogs
2, is there anyway to bring blogs in place of tags

**Comment by PippoRJ** [comment]
Hi there!

There is an option in the config file to show a home button in the top
navbar in each blog post. Please have a look at the config file.

No sorry, currently there is no option to bring the list of blog posts
instead of the list of tags.
