### ISSUE TITLE
Error with call to IsSet

### ISSUE THREAD

**Issue by icifra** [PippoRJ/hugo-refresh#86]
When building the site, I get the following error::

"WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false."

Hugo forum discussion: https://discourse.gohugo.io/t/error-with-call-to-isset/42742

Author assistance required

**Comment by PippoRJ** [comment]
Hi @icifra ,
I think the theme will always issue that warning as I might use that function not in the usual way. Nevertheless as far as I have tested it should be running ok.
If you get other issues let me know.
