### ISSUE TITLE
How to properly set up multilingual support

### ISSUE THREAD

**Issue by icifra** [PippoRJ/hugo-refresh#87]
Let's say I want to change the default language "en" to "de" (or another one from i18n) , then my changes should be as follows: 

1. `languageCode: de` (do I need to change this setting at all?);
2. `DefaultContentLanguage: de`; 
3. `disableLanguages: ["en"]` (this is optional but to disable the default language and leave only one language);
4. It turns out that the general settings of the home page `homepage:` and `footer:` do not need to be changed, because language "en" is disabled (item 3);
5. Parameter `languages:` do not change and two languages remain here: English - 1 and Deutsch - 2;
6. And already in the "Multilingual support options" section, we change the `homepage:` and `footer:` parameters to suit your language.

Is this the correct order?

**Comment by PippoRJ** [comment]
hi @icifra , sorry for the very late reply.
You can find an example of multilingual configuration in the example site of this theme.
For other configuration there is a hugo page: https://gohugo.io/content-management/multilingual/
