### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by icifra** [PippoRJ/hugo-refresh#89]
The button to return to the top of the page displays a rectangle.

Is this button working properly or is something not working properly?

![button](https://user-images.githubusercontent.com/99347099/217818619-6cbc07e0-943a-4c47-bd75-40acc3adc1f2.png)

**Comment by PippoRJ** [comment]
yes something is not working properly. I need to have a look at it.

**Comment by PippoRJ** [comment]
It should be fixed with the new CSS
