### ISSUE TITLE
Multilingual theme

### ISSUE THREAD

**Issue by PippoRJ** [PippoRJ/hugo-refresh#9]
> Hi, thanks for the great theme and the ability to display the static pages in the menu. 
> Is it possible to allow translation of the generated menu items into another language?

_Originally posted by @vBuresh in https://github.com/PippoRJ/hugo-refresh/issues/3#issuecomment-548066824_

**Comment by PippoRJ** [comment]
Hi @vBuresh 

I am reporting to the new issue that you wrote previously:

> Hi Roberto!
> 
> Thanks for your prompt reply and helpfulness.
> So far, creating multilingual sites for me is tomorrow's task, but it is very interesting. I look at her, including [discussions ](https://discourse.gohugo.io/t/translation-of-the-plural-and-zero-in-russian-returns-the-name-of-the-variable/14995).
> 
> But now I need translation of a few interface elements only:
> - Main menu (usually 2-5 positions)
> - other items (5 positions)
>     1. /layouts/partials/single/summary.html  
>     **Read More** to **Читать...**
>     2. /layouts/partials/single/summary.html  
>     **Read More** to **Читать...**
>     3. /layouts/partials/single/navbar-clone.html  
>     /layouts/partials/navbar.html
>     **Menu** to **Меню**
>     4. /layouts/partials/single/summary.html  
>     **All Tags** to **Все теги**
>     5. /layouts/partials/single/content.html  
>     **Last modified:** to **Обновлено:**
> 
> To translate user interface terms I crawled into the source code. But this is the wrong method. Better to make the settings. Unfortunately, my skills do not yet allow me to do this myself.
> 
> However, I tried to make the necessary changes in the code (except for menu items - by the names of the / content subdirectories). It works. Only when scrolling there are arbitrary switching between **Menu** and **Меню** 
> 
> And yet, it’s important to have a date format setting for: 
> `Last modified: {{- .Lastmod.Format "2 January 2006" -}}`
> 
> Thank you again for the wonderful, very concise, elegant theme.

Yes, you are right. 
Those words are not configured to be changed. I will dig into how to add the multilingual feature but it might take a while to implement it. 
When you start to implement the multilingual site, if I didn't implement this feature yet, please ping me up again!

**Comment by vBuresh** [comment]
Thank you for your attention to this matter. I sincerely wish you all success.

**Comment by PippoRJ** [comment]
Hi @vBuresh,
I merged your commit thus adding the multilanguage support for the theme.
Let me know if you find other issues.
