### ISSUE TITLE
Google Fonts local

### ISSUE THREAD

**Issue by ruben-herold** [PippoRJ/hugo-refresh#91]
hi,

is it possible to host the google fonts local without requesting them from the google servers?
Loading them from the google servers is a GDPR problem see https://meetanshi.com/blog/google-fonts-gdpr-compliant/.

**Comment by PippoRJ** [comment]
Hi,
That's a good idea.
I am overloaded with work this period, not sure how much I can work on it.
But I will keep this open as a reminder.

**Comment by ruben-herold** [comment]
@PippoRJ thx can you give me some hints how todo, so I could try to add it.

**Comment by PippoRJ** [comment]
@ruben-herold I have added the support for local fonts

**Comment by ruben-herold** [comment]
Thank your very much!!!
